set title 'Tube center positions'
set xlabel 'x [cm]'
set ylabel 'z [cm]'
set zlabel 'y [cm]'
splot 'T1X.dat' u 1:3:2 t 'T1X', 'T1U.dat' u 1:3:2 t 'T1U', 'T2X.dat' u 1:3:2 t 'T2X', 'T2V.dat' u 1:3:2 t 'T2V'
